name: Integ

on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        default: 'master'

jobs:
  integ:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.15
          - ubuntu-18.04
          - windows-2019
        emacs-version:
          - '27.2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: purcell/setup-emacs@v3.0
        if: runner.os != 'Windows'
        with:
          version: ${{ matrix.emacs-version }}
      # Seems like the Emacs archive from GNU's FTP uses its own outdated bundle of CA certs, which
      # wouldn't include the new LetsEncrypt's root CA cert, which is used by MELPA, among others.
      # So we use mingw64's Emacs instead. TODO: Switch back whenever possible.
      - name: Install Emacs (Windows)
        if: runner.os == 'Windows'
        run: |
          $env:MSYS_PATH = "$env:CD\ci-tools\msys2"
          choco install msys2 --params="/InstallDir:$env:MSYS_PATH /NoPath"
          $env:PATH = "$env:MSYS_PATH\usr\bin;" + $env:PATH
          pacman -S --noconfirm --needed mingw-w64-x86_64-emacs
          echo "$env:MSYS_PATH\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf-8 -Append

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.revision }}

      - run: .github/script/setup-cask
      - run: bin/setup

      - run: bin/test integ
